version = 0.1
[default.deploy.parameters]
stack_name = "resume"
resolve_s3 = true
s3_prefix = "resume"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
